/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.5-342
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    CallParams,
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3';


// Services

export interface IOnboardingServiceDef {
    get_location_game: (onboardInput: { arcade: string; arcadeSize: string; banner: string; description: string; developer: string; facebook: string; gameName: string; gameURL: string; genre: string[]; instagram: string; linkedin: string; screenshot: string[]; twitter: string; wallet: string; youtube: string; }, callParams: CallParams<'onboardInput'>) => { height: number; inputData: { arcade: string; arcadeSize: string; banner: string; description: string; developer: string; facebook: string; gameName: string; gameURL: string; genre: string[]; instagram: string; linkedin: string; screenshot: string[]; twitter: string; wallet: string; youtube: string; }; location_id: string; status: { message: string; status_code: number; success: boolean; }; width: number; x: number; y: number; } | Promise<{ height: number; inputData: { arcade: string; arcadeSize: string; banner: string; description: string; developer: string; facebook: string; gameName: string; gameURL: string; genre: string[]; instagram: string; linkedin: string; screenshot: string[]; twitter: string; wallet: string; youtube: string; }; location_id: string; status: { message: string; status_code: number; success: boolean; }; width: number; x: number; y: number; }>;
    insert_arcade_building: (arcade_detail: { height: number; inputData: { arcade: string; arcadeSize: string; banner: string; description: string; developer: string; facebook: string; gameName: string; gameURL: string; genre: string[]; instagram: string; linkedin: string; screenshot: string[]; twitter: string; wallet: string; youtube: string; }; location_id: string; status: { message: string; status_code: number; success: boolean; }; width: number; x: number; y: number; }, callParams: CallParams<'arcade_detail'>) => { buildingId: string; locationId: string; status: { message: string; status_code: number; success: boolean; }; wallet: string; } | Promise<{ buildingId: string; locationId: string; status: { message: string; status_code: number; success: boolean; }; wallet: string; }>;
    update_mongodb_location: (locationDetail: { buildingId: string; locationId: string; status: { message: string; status_code: number; success: boolean; }; wallet: string; }, callParams: CallParams<'locationDetail'>) => { message: string; status_code: number; success: boolean; } | Promise<{ message: string; status_code: number; success: boolean; }>;
}
export function registerIOnboardingService(service: IOnboardingServiceDef): void;
export function registerIOnboardingService(serviceId: string, service: IOnboardingServiceDef): void;
export function registerIOnboardingService(peer: FluencePeer, service: IOnboardingServiceDef): void;
export function registerIOnboardingService(peer: FluencePeer, serviceId: string, service: IOnboardingServiceDef): void;
       

export function registerIOnboardingService(...args: any) {
    registerService(
        args,
        {
    "defaultServiceId" : "onboardingservice",
    "functions" : {
        "tag" : "labeledProduct",
        "fields" : {
            "get_location_game" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "onboardInput" : {
                            "tag" : "struct",
                            "name" : "OnboardInput",
                            "fields" : {
                                "arcadeSize" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "genre" : {
                                    "tag" : "array",
                                    "type" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                },
                                "description" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "linkedin" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "developer" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "facebook" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "screenshot" : {
                                    "tag" : "array",
                                    "type" : {
                                        "tag" : "scalar",
                                        "name" : "string"
                                    }
                                },
                                "twitter" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "arcade" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "instagram" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "wallet" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "youtube" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "gameName" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "gameURL" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "banner" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "ArcadeDetail",
                            "fields" : {
                                "x" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "y" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "height" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "location_id" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status" : {
                                    "tag" : "struct",
                                    "name" : "StatusMessage",
                                    "fields" : {
                                        "message" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "status_code" : {
                                            "tag" : "scalar",
                                            "name" : "f32"
                                        },
                                        "success" : {
                                            "tag" : "scalar",
                                            "name" : "bool"
                                        }
                                    }
                                },
                                "width" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "inputData" : {
                                    "tag" : "struct",
                                    "name" : "OnboardInput",
                                    "fields" : {
                                        "arcadeSize" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "genre" : {
                                            "tag" : "array",
                                            "type" : {
                                                "tag" : "scalar",
                                                "name" : "string"
                                            }
                                        },
                                        "description" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "linkedin" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "developer" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "facebook" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "screenshot" : {
                                            "tag" : "array",
                                            "type" : {
                                                "tag" : "scalar",
                                                "name" : "string"
                                            }
                                        },
                                        "twitter" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "arcade" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "instagram" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "wallet" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "youtube" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "gameName" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "gameURL" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "banner" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        }
                                    }
                                }
                            }
                        }
                    ]
                }
            },
            "insert_arcade_building" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "arcade_detail" : {
                            "tag" : "struct",
                            "name" : "ArcadeDetail",
                            "fields" : {
                                "x" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "y" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "height" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "location_id" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status" : {
                                    "tag" : "struct",
                                    "name" : "StatusMessage",
                                    "fields" : {
                                        "message" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "status_code" : {
                                            "tag" : "scalar",
                                            "name" : "f32"
                                        },
                                        "success" : {
                                            "tag" : "scalar",
                                            "name" : "bool"
                                        }
                                    }
                                },
                                "width" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "inputData" : {
                                    "tag" : "struct",
                                    "name" : "OnboardInput",
                                    "fields" : {
                                        "arcadeSize" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "genre" : {
                                            "tag" : "array",
                                            "type" : {
                                                "tag" : "scalar",
                                                "name" : "string"
                                            }
                                        },
                                        "description" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "linkedin" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "developer" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "facebook" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "screenshot" : {
                                            "tag" : "array",
                                            "type" : {
                                                "tag" : "scalar",
                                                "name" : "string"
                                            }
                                        },
                                        "twitter" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "arcade" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "instagram" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "wallet" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "youtube" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "gameName" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "gameURL" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "banner" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "LocationDetail",
                            "fields" : {
                                "buildingId" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "locationId" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status" : {
                                    "tag" : "struct",
                                    "name" : "StatusMessage",
                                    "fields" : {
                                        "message" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "status_code" : {
                                            "tag" : "scalar",
                                            "name" : "f32"
                                        },
                                        "success" : {
                                            "tag" : "scalar",
                                            "name" : "bool"
                                        }
                                    }
                                },
                                "wallet" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    ]
                }
            },
            "update_mongodb_location" : {
                "tag" : "arrow",
                "domain" : {
                    "tag" : "labeledProduct",
                    "fields" : {
                        "locationDetail" : {
                            "tag" : "struct",
                            "name" : "LocationDetail",
                            "fields" : {
                                "buildingId" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "locationId" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status" : {
                                    "tag" : "struct",
                                    "name" : "StatusMessage",
                                    "fields" : {
                                        "message" : {
                                            "tag" : "scalar",
                                            "name" : "string"
                                        },
                                        "status_code" : {
                                            "tag" : "scalar",
                                            "name" : "f32"
                                        },
                                        "success" : {
                                            "tag" : "scalar",
                                            "name" : "bool"
                                        }
                                    }
                                },
                                "wallet" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                }
                            }
                        }
                    }
                },
                "codomain" : {
                    "tag" : "unlabeledProduct",
                    "items" : [
                        {
                            "tag" : "struct",
                            "name" : "StatusMessage",
                            "fields" : {
                                "message" : {
                                    "tag" : "scalar",
                                    "name" : "string"
                                },
                                "status_code" : {
                                    "tag" : "scalar",
                                    "name" : "f32"
                                },
                                "success" : {
                                    "tag" : "scalar",
                                    "name" : "bool"
                                }
                            }
                        }
                    ]
                }
            }
        }
    }
}
    );
}
      
// Functions

